# -*- coding: utf-8 -*-
"""3rd_expeiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrwUsEkbm2PNNnyVtT0fxXoqY4c81wiR
"""

# ===========================================
# Step 1: Import Libraries
# ===========================================

import pandas as pd
import numpy as np
from google.colab import files
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

# ===========================================
# Step 2: Upload CSV File
# ===========================================

uploaded = files.upload()

file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name)

print("CSV File Uploaded Successfully!\n")

# ===========================================
# Step 3: Display Dataset
# ===========================================

print(df.head())

# ===========================================
# Step 4: Check Missing Values
# ===========================================

print("\nMissing Values:")
print(df.isnull().sum())

# ===========================================
# Step 5: Fill Missing Values
# ===========================================

# Convert 'Calories' to numeric, coercing errors to NaN
if 'Calories' in df.columns:
    df['Calories'] = pd.to_numeric(df['Calories'], errors='coerce')

# Update numeric_cols after ensuring 'Calories' is numeric
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    if df[col].isnull().any(): # Only fill if there are missing values
        df[col].fillna(df[col].mean(), inplace=True)

print("\nMissing Values Filled!")

# ===========================================
# Step 6: Remove Duplicate Records
# ===========================================

print("\nDuplicate Rows:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("Duplicates Removed!")

# ===========================================
# Step 7: Detect Outliers (Calories)
# ===========================================

if 'Calories' in df.columns:

    Q1 = df['Calories'].quantile(0.25)
    Q3 = df['Calories'].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df['Calories'] < lower) | (df['Calories'] > upper)]

    print("\nOutliers:")
    print(outliers)

# ===========================================
# Step 8: Normalize Numeric Columns
# ===========================================

scaler = MinMaxScaler()

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print("\nNormalization Completed!")

# ===========================================
# Step 9: Encode Categorical Columns
# ===========================================

encoder = LabelEncoder()

cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = encoder.fit_transform(df[col].astype(str))

print("\nEncoding Completed!")

# ===========================================
# Step 10: Final Dataset
# ===========================================

print(df.head())